# Generated by Django 3.1.3 on 2020-11-07 12:29

from django.db import migrations


def create_skeleton_menu(apps, schema_editor):
    categories = [
        (1, 'Breakfast', 'Breakfast served unil 11am.'),
        (2, 'Lunch', 'Lunch available from 11am.'),
        (3, 'Drinks', 'Hot and cold drinks.'),
        (4, 'Snacks', 'Variety of snacks available.'),
        (5, 'Bakery', 'Fresh baked every day.'),
    ]

    for (id, name, description) in categories:
        MenuCategory = apps.get_model('frontend', 'MenuCategory')
        mc = MenuCategory(id=id, name=name, description=description)
        mc.save()


def delete_menu(apps, schema_editor):
    MenuCategory = apps.get_model('frontend', 'MenuCategory')
    MenuCategory.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20201107_1420'),
    ]

    operations = [
        migrations.RunPython(create_skeleton_menu, delete_menu),
    ]
