# Generated by Django 3.1.3 on 2020-11-07 12:29

from django.db import migrations


def create_skeleton_menu(apps, schema_editor):
    categories = [
        ('Breakfast', 'Breakfast served unil 11am.'),
        ('Lunch', 'Lunch available from 11am.'),
        ('Drinks', 'Hot and cold drinks.'),
        ('Snacks', 'Variety of snacks available.'),
        ('Bakery', 'Fresh baked every day.'),
    ]

    for (name, description) in categories:
        MenuCategory = apps.get_model('frontend', 'MenuCategory')
        mc = MenuCategory(name=name, description=description)
        mc.save()


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20201107_1420'),
    ]

    operations = [
        migrations.RunPython(create_skeleton_menu),
    ]
