# Generated by Django 3.1.3 on 2020-11-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20201107_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='item_image_1',
            field=models.ImageField(default='None', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='item_image_2',
            field=models.ImageField(default='None', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='item_image_3',
            field=models.ImageField(default='None', upload_to=''),
            preserve_default=False,
        ),
    ]
