# Generated by Django 3.1.3 on 2020-11-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20201107_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='item_image_1',
            field=models.ImageField(upload_to='', verbose_name='Image #1'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='item_image_2',
            field=models.ImageField(upload_to='', verbose_name='Image #2'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='item_image_3',
            field=models.ImageField(upload_to='', verbose_name='Image #3'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='order',
            name='tip_total',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
    ]
