# Generated by Django 3.1.3 on 2020-11-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20201116_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='notes',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
