# Generated by Django 3.1.3 on 2020-12-18 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_auto_20201116_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='item_image_1',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Image #1'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='item_image_2',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Image #2'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='item_image_3',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Image #3'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(choices=[('Deliver', 'Deliver'), ('Collect', 'Collect')], max_length=16),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='order',
            name='tip_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=11)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card')], max_length=32)),
                ('notes', models.CharField(blank=True, max_length=150)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('mdate', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.order')),
            ],
        ),
    ]
