# Generated by Django 3.1.3 on 2020-12-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_auto_20201218_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='item_image_1',
            field=models.ImageField(blank=True, upload_to='frontend/static/menu', verbose_name='Image #1'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='item_image_2',
            field=models.ImageField(blank=True, upload_to='frontend/static/menu', verbose_name='Image #2'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='item_image_3',
            field=models.ImageField(blank=True, upload_to='frontend/static/menu', verbose_name='Image #3'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='special_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
    ]
